services:

  inventory-api:
    image: moody/inventory_server:latest
    container_name: cmoon_inventory
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ansible:
    image: moody/cmoon:latest
    container_name: cmoon
    restart: unless-stopped
    environment:
      - PUBLIC_KEY=${PUBLIC_KEY}
      - USER_NAME=${USER_NAME}
    volumes:
      - ./inventory:/ansible/inventory/
      - ./roles:/ansible/roles/
      - ./playbook:/ansible/playbook/
      - ./keys:/ansible/keys

  shigechi-1: &common
    image: linuxserver/openssh-server
    container_name: shigechi-1
    restart: unless-stopped
    env_file: ".env"
    environment:
      - PUBLIC_KEY=${PUBLIC_KEY}
      - USER_NAME=${USER_NAME}
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./sshd_config:/config/sshd/sshd_config


  shigechi-2: 
    <<: *common
    container_name: shigechi-2


  shigechi-3: 
    <<: *common
    container_name: shigechi-3

  shigechi-4: 
    <<: *common
    container_name: shigechi-4